#!/bin/bash

VERSION=${1}
DOCKERHUB_PASSWORD=${2}
DOCKERHUB_USERNAME=${3}

APP_NAME_NISTAGRAM_USERS=nistagram-users

APP_IMAGE_NAME_NISTAGRAM_USERS=${DOCKERHUB_USERNAME}/${APP_NAME_NISTAGRAM_USERS}:${VERSION}

APP_ARTIFACT_NAME_NISTAGRAM_USERS=${APP_NAME_NISTAGRAM_USERS}:${VERSION}.tar

DOCKER_BUILDKIT=1 docker build \
-t "${APP_IMAGE_NAME_NISTAGRAM_USERS}" \
--no-cache \
.

docker login --username ${DOCKERHUB_USERNAME} --password=${DOCKERHUB_PASSWORD}
docker push "$APP_IMAGE_NAME_NISTAGRAM_USERS"