version: '3.7'

services:
  nistagram-users-db:
    container_name: nistagram-users-db
    image: mysql:8.0.19
    restart: always
    ports:
      - 3306
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nistagramusersschema

  nistagram-users-test:
    container_name: nistagram-users-test
    build:
      dockerfile: Dockerfile.test
      context: .
    depends_on:
      nistagram-users-db:
          condition: service_healthy
    environment:
      - mysql_username=root
      - mysql_password=root
      - mysql_host=nistagram-users-db:3306
      - mysql_schema=nistagramusersschema