name: Main CI workflow
on:
  pull_request_review:
    types: [submitted]

jobs:
  CI:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create semantic version
      id: versioning
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: ""
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}"
        short_tags: false
        bump_each_commit: true
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Build image and publish to DockerHub
      run: |
        chmod 777 ./build-upload-publish.sh
        ./build-upload-publish.sh ${{ steps.versioning.outputs.version }} ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_USERNAME }}
    - name: Build nistagram-users artifact
      working-directory: .
      run: go build -o ./nistagram-users-${{ steps.versioning.outputs.version }}.exe ./src/main.go
    - name: Upload nistagram-users backend artifact to repository
      uses: actions/upload-artifact@v2
      with:
        name: nistagram-users-${{ steps.versioning.outputs.version }}
        path: ./nistagram-users-${{ steps.versioning.outputs.version }}.exe